CREATE TABLE Person (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR NOT NULL,
    Age INTEGER NOT NULL,
    DriverLicense INTEGER DEFAULT (0)
);
CREATE TABLE Car (
    PersonId SERIAL PRIMARY KEY,
    Brand VARCHAR NOT NULL,
    Model VARCHAR NOT NULL,
    Price NUMERIC,
    CarId INTEGER NOT NULL REFERENCES Person(Id)
);